name: QA Report Form
description: Feedback form for QA Team
title: "Give this QA report a title"
body:
  - type: input
    id: view
    attributes:
      label: If Client side, what view is this feedback for?
      description: What view is this feedback for?
    validations:
      required: false
  - type: dropdown
    id: ui-ux
    attributes:
      label: Category
      description: Select from dropdown below.
      multiple: true
      options:
        - Copy (ie. grammar, spelling, punctuation.)
        - Design (ie. color, font, spacing.)
        - Functionality
    validations:
      required: true
  - type: textarea
    id: replication-steps
    attributes:
      label: Replication steps
      description: Please provide steps to replicate the issue. If you have a video (i.e. Loom) or screenshots please add them here.
    validations:
      required: true
  - type: dropdown
    id: test-flight
    attributes:
      label: Submitted to Test Flight? (iOS only)
      description: Select from dropdown below.
      options:
        - 'Yes'
        - 'No'
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell